### ISSUE TITLE
Set load model = True,but it doesn't work?

### ISSUE THREAD

**Issue by cn-actor** [sgawalsh/dqnTurtlebot#4]
Hello,I set loadmodel = True,copy trained model to folder load_model and set ε = 1，ε decay = 1,but it feels like training from start.

**Comment by sgawalsh** [comment]
The way that the epsilon decay works in this project is at the end of each episode, the epsilon value is multiplied by the epsilon decay value to slightly reduce the epsilon value, until the epsilon minimum value is reached.

The epsilon value controls when the action taken is generated by the neural net, or when the action is selected randomly, the higher the epsilon value is the more likely a random value will be chosen. The code for this is in the [getAction function](https://github.com/sgawalsh/dqnTurtlebot/blob/master/turt_q_learn/scripts/turt_q_learn_hypers.py#L58). This is to ensure that the agent explores different behaviours and does get stuck in a localized inefficient solution.

With your variables, the epsilon value would remain at 1, and the action would always be chosen randomly, so that's why it would appear to be untrained. To see the model perform with no random actions simply set epsilon to 0.

**Comment by cn-actor** [comment]
> The way that the epsilon decay works in this project is at the end of each episode, the epsilon value is multiplied by the epsilon decay value to slightly reduce the epsilon value, until the epsilon minimum value is reached.
> 
> The epsilon value controls when the action taken is generated by the neural net, or when the action is selected randomly, the higher the epsilon value is the more likely a random value will be chosen. The code for this is in the [getAction function](https://github.com/sgawalsh/dqnTurtlebot/blob/master/turt_q_learn/scripts/turt_q_learn_hypers.py#L58). This is to ensure that the agent explores different behaviours and does get stuck in a localized inefficient solution.
> 
> With your variables, the epsilon value would remain at 1, and the action would always be chosen randomly, so that's why it would appear to be untrained. To see the model perform with no random actions simply set epsilon to 0.

Appreciate your reply so much!: )Yeah!Totally understood!I just learn ε-greedy two days ago.I'm a little ...HAHA.Thanks again!
